In [3]:
!pip install numpy

In [4]:
!pip install pandas

In [5]:
!pip install matplotlib

In [6]:
!pip install seaborn

In [7]:
import numpy as np
arr=np.array([1,2,3])
print(arr)
type(arr)

[1 2 3]


numpy.ndarray

In [9]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [10]:
ab=np.array([[[1,2,3]]])
print(ab)

[[[1 2 3]]]


In [11]:
print(arr.size)
print(a.size)
print(ab.size)

3
9
3


In [12]:
print(arr.shape)
print(a.shape)
print(ab.shape)

(3,)
(1, 3, 3)
(1, 1, 3)


In [16]:
import pandas as pd
s=pd.Series([1,2,3,4],index=['a','b','c','d'],name="experiment")
print(s)

a    1
b    2
c    3
d    4
Name: experiment, dtype: int64


In [20]:
s.iloc[3]

4

In [21]:
df=pd.DataFrame([4,5,6,7,8,9])
print(df)

   0
0  4
1  5
2  6
3  7
4  8
5  9


In [25]:
df2=pd.DataFrame([[1,2,3],[4,5,6]])
print(df2)

   0
4  1
5  2
6  3


In [30]:
a={'Roll no.': pd.Series([1,2,3,4,5]),
   'marks':pd.Series([95,34,98,97,36]),
   'grade':pd.Series(['A','P','A','A','P'])}
df3=pd.DataFrame(a)
print(df3)


   Roll no.  marks grade
0         1     95     A
1         2     34     P
2         3     98     A
3         4     97     A
4         5     36     P


In [31]:
df4=pd.read_csv(r'C:\Users\91901\Desktop\ai ml\.ipynb_checkpoints\month.csv')
print(df4)

         Name Abbreviation  Numeric  Numeric-2
0     January         Jan.        1          1
1    Feburary         Feb.        2          2
2       March         Mar.        3          3
3       April         Apr.        4          4
4         May          May        5          5
5        June         June        6          6
6        July         July        7          7
7      August         Aug.        8          8
8   September        Sept.        9          9
9     October         Oct.       10         10
10   November         Nov.       11         11
11   December         Dec.       12         12


In [34]:
df5=pd.read_csv(r'C:\Users\91901\Desktop\ai ml\.ipynb_checkpoints\sample.csv')
df5.head()

Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      26.0
2         3     89.0       25.0   26.0      27.0
3         4     45.0       26.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0

In [35]:
df5.isnull().sum()

Roll No.     0
Physics      3
Chemistry    4
Maths        2
Computer     1
dtype: int64

In [36]:
df5.isnull().sum().sum()

10

In [41]:
df6=df5.dropna()
df5.size

150

In [42]:
df6.size

110

In [43]:
df5=pd.read_csv(r'C:\Users\91901\Desktop\ai ml\.ipynb_checkpoints\sample.csv',index_col=['Roll No.'])
df5.head()

Physics  Chemistry  Maths  Computer
Roll No.                                     
1            56.0       57.0   58.0      59.0
2            23.0       24.0   25.0      26.0
3            89.0       25.0   26.0      27.0
4            45.0       26.0   27.0      28.0
5            23.0       27.0   28.0      29.0