In [3]:
import numpy as np
import pandas as pd

In [5]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [13]:
df=pd.read_csv('covid dataset.csv')
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [21]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [25]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [27]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [53]:
from sklearn.model_selection import train_test_split
xtr,xte,ytr,yte=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [55]:
xtr.head()

age  gender  fever   cough       city
61   81  Female   98.0  Strong     Mumbai
13   64    Male  102.0    Mild  Bangalore
17   40  Female   98.0  Strong      Delhi
38   49  Female  101.0    Mild      Delhi
46   19  Female  101.0    Mild     Mumbai

In [63]:
si = SimpleImputer()
xtrfe=si.fit_transform(xtr[['fever']])
xtefe=si.fit_transform(xte[['fever']])
xtrfe.shape                              

(80, 1)

In [51]:
xte.head()

80    Yes
36     No
66     No
79    Yes
46     No
Name: has_covid, dtype: object

In [89]:
ohe = OneHotEncoder(drop='first',sparse_output=False)
xtrgenci= ohe.fit_transform(xtr[['gender','city']])
xtegenci= ohe.fit_transform(xte[['gender','city']])
xtrgenci

array([[0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],


In [91]:
xtrage =xtr.drop(columns=['gender','fever','cough','city']).values
xteage =xte.drop(columns=['gender','fever','cough','city']).values
xtrage.shape

(80, 1)

In [93]:
oe = OrdinalEncoder(categories=[['Mild','Strong']])
xtrcough = oe.fit_transform(xtr[['cough']])
xtecough = oe.fit_transform(xte[['cough']])
xtrcough

array([[1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],

In [98]:
xtrtransformed = np.concatenate((xtrage,xtrfe,xtrgenci,xtrcough),axis=1)
xtesttransformed = np.concatenate((xteage,xtefe,xtegenci,xtecough),axis=1)
xtrtransformed

array([[ 81.   ,  98.   ,   0.   ,   0.   ,   0.   ,   1.   ,   1.   ],
       [ 64.   , 102.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [ 40.   ,  98.   ,   0.   ,   1.   ,   0.   ,   0.   ,   1.   ],
       [ 49.   , 101.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 19.   , 101.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ],
       [ 14.   , 101.   ,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ],
       [ 27.   , 100.   ,   1.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 51.   , 101.   ,   0.   ,   0.   ,   1.   ,   0.   ,   1.   ],
       [ 51.   , 104.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [  5.   , 100.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 26.   ,  98.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 73.   ,  98.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [ 69.   , 102.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [ 48.   , 103.   ,   0.   ,   0.   ,   1.   ,   0.   ,   

In [ ]:
#or

In [135]:
from sklearn.compose import ColumnTransformer

In [151]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [153]:
transformer.fit_transform(xtr).shape

(80, 7)